version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop-V2"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    groups:
      root-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "npm"
    directory: "/backend"
    target-branch: "develop-V2"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    groups:
      backend-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "develop-V2"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    groups:
      frontend-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(deps)"
